# Generated by Django 4.2.1 on 2024-05-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_coursedetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=50)),
                ("link", models.TextField()),
                ("subject", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="coursedetail",
            name="className",
            field=models.CharField(default="", max_length=50),
        ),
    ]
